# Generated by Django 4.2.1 on 2024-04-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_feedback_date_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
