# Generated by Django 4.2.1 on 2024-04-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_category_options_remove_animal_age_animal_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
