# Generated by Django 4.2.1 on 2024-04-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_rename_name_animal_title_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='animal',
        ),
    ]
