# Generated by Django 4.2.1 on 2024-04-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_rename_category_category_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
    ]
