# Generated by Django 4.2.2 on 2024-05-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_category_category_category_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='В наличии'),
        ),
    ]
